name: CI

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  MOZBUILD_STATE_PATH: /home/runner/.mozbuild

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Bootstrap
        run: |
          mkdir /home/runner/.mozbuild
          ./mach bootstrap --no-interactive --application-choice browser
      - name: Build
        run: ./mach build
